### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by helper-uttam**
Adding typewritter effect

### CODE REVIEW

**Comment by deepakkumar-platform** [comment]
> Adding typewritter effect

Thank you for your help

**Comment by helper-uttam** [comment]
I saw the tags that you had used for your social media handles. Can you please do the same at my github profile by replacing the existing icons of social media handles.

**Comment by deepakkumar-platform** [comment]
> I saw the tags that you had used for your social media handles. Can you please do the same at my github profile by replacing the existing icons of social media handles.

Done, I made a PR request check it

**Comment by helper-uttam** [comment]
> > I saw the tags that you had used for your social media handles. Can you please do the same at my github profile by replacing the existing icons of social media handles.
> 
> Done, I made a PR request check it

nopes, please check from your side. Because PR is not raised yet !

**Comment by deepakkumar-platform** [comment]
Sorry. Check it now

**Pull request merged**
